---
title: "A soft intro to Python (part II)"
format: 
  revealjs:
    theme: dark
    smaller: true
jupyter: python3
---


## Homework :)

Generate a list of integers, and then show:

- the list

- the list in column format, displaying matching keys and values

- the sum of all elements of the list

- create a new list made of 5 multiples of the original list

- give min and max values of the list

- count occurrences of pair and odd numbers and sum them

You can find all answers on this shared [Colab](https://colab.research.google.com/drive/1RDBkYlQ8f4Fbab8ztlRFgCwVPypAV4B0). 

Try it out !




## Generate a list of integers, and show:

1. The list:

```{python}
#| echo: true
#| eval: true
# I didn't specify anything, so this is valid:
mylist = list(range(11, 20))

# show list
mylist


```

```{python}
#| echo: true
#| eval: true
# But you *could* use the random library:
import random
randlist = random.sample(range(11, 50), 9)

# show list
randlist

```

## Generate a list of integers, and show:

2. The list in column format:

```{python}


# the list displaying matching keys and values
length = len(randlist)
for i in range(length):
  print(i, ":", randlist[i])

```

3. The sum of all elements of the list, and the minimum and maximum values of the list

```{python}
#| echo: true
#| eval: true
print("sum randlist = ", sum(randlist), "; max randlist = ", max(randlist), "; min randlist = ", min(randlist))
```



## Generate a list of integers, and show:

4. Create a new list made of 5 multiples of the original list

```{python}
#| echo: true
#| eval: true

listx5 = []

for i in randlist:
  listx5.append(i*5)
print("multiples list : ", listx5)
```


## Generate a list of integers, and show:

5. Count odd and even numbers

```{python}
#| echo: true
#| eval: true

npairs = 0
nodd = 0
for i in randlist:
  if i%2 == 1:
    npairs += 1
  else:
    nodd += 1
print("randlist has", npairs, "pair numbers and", nodd, "odd numbers.")
```
.

.

.

### Tudo bem ??

## Let's write some functions...


## Let's write some functions...


Syntax:

==> note INDENT, and the `:`

```python
def add_two(a) :
  return a + 2

add_two(2) # 4

add_two(50) # 52
```




























